info:
  root: ../data/

dag:
  tasks:
    - name: A
      template: template_name
      parameters:
      arguments_type: float
      returns_type: float
      depends: NO
    - name: B
      template: template_name
      parameters:
        foo: 10
        bar: string
      arguments: { name }
    - name: C
      template:
      parameters:
      arguments_type: [float, float, float]
      return_type: float
