info: ""
dag:
  node_a:
    name: node_a
    content:
      _target_: __main__.generate_random
      _partial_: true
      start: 10
      finish: 30
    edges:
      - node_b1.n
      - node_b2.a
  node_b1:
    name: node_b1
    content:
      _target_: __main__.fib_func
      _partial_: true
    edges:
      - node_c.a
  node_b2:
    name: node_b2
    content:
      _target_: __main__.square_func
      _partial_: true
    edges:
      - node_c.b
  node_c:
    name: node_c
    content:
      _target_: __main__.sum_func
      _partial_: true
    edges: []
