info: {}
dag:
  node_a:
    name: node_a
    content:
      _target_: random.random
      _partial_: true
    variables: null
    edges:
    - node_b.x
    - node_c.x
  node_b:
    name: node_b
    content:
      _target_: __main__.tan
      _partial_: true
    variables:
      x:
        type: None
        value: 0.6448728169288591
    edges:
    - node_d.x
  node_c:
    name: node_c
    content:
      _target_: __main__.my_pow
      _partial_: true
      dummy:
        _target_: __main__.MyPow
        base: 2
    variables:
      x:
        type: None
        value: 0.6448728169288591
    edges:
    - node_d.y
  node_d:
    name: node_d
    content:
      _target_: __main__.my_sum
      _partial_: true
    variables:
      x:
        type: None
        value: 0.7521455025599701
      'y':
        type: None
        value: 0.41586095001376183
    edges: []
